from scripts.query_price import query_price
from scripts.update_old_data import update_old_data
from scripts.request_wrapper import send_response
from scripts.query_price_scripts.parse_response_query import append_cards